### ISSUE TITLE
Morning Session: 25 Nov 2020

### ISSUE THREAD

**Issue by SuyashFowdar** [Zappat0n/tic-tac-toe#4]
**Good till now.**

## A few changes can be implemented:
- Remove classes and keep it simple for Milestone 2
- Remove the logic for invalid moves, draw and win. Just put specific conditions, or make the messages appear randomly.
- The code complexity can be simplified, even for the milestone 3

Have fun with that! 

Thank you guys!

**Comment by Zappat0n** [comment]
Changes implemented. Thank you!
